# -----------------------------------------------------------------------------
# Copyright (c) 2026, Oracle and/or its affiliates.
#
# This software is dual-licensed to you under the Universal Permissive License
# (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl and Apache License
# 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose
# either license.
#
# If you elect to accept the software under the Apache License, Version 2.0,
# the following applies:
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# settings.py
#
# Django settings for the Deep Data Security sample application using
# python-oracledb, Oracle Database, and Microsoft Entra ID authentication.
# -----------------------------------------------------------------------------

"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import pathlib
import sys

from django.core.exceptions import ImproperlyConfigured

path = pathlib.Path(__file__)
sys.path.insert(0, str(path.parent.parent.parent.parent.parent.parent))

try:
    import sample_env
except ImportError as exc:
    raise ImproperlyConfigured(
        "Could not import 'sample_env'. Ensure sample_env.py is on PYTHONPATH "
        "(for example from python-oracledb/samples) or update DATABASES config "
        "to use environment-based DB settings."
    ) from exc


def get_required_env_value(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(
            f"Missing required environment variable: {name}"
        )
    return value


# Azure credentials for user token acquisition
AZURE_USER_CLIENT_ID = get_required_env_value("AZURE_USER_CLIENT_ID")
AZURE_USER_CLIENT_CREDENTIAL = get_required_env_value(
    "AZURE_USER_CLIENT_CREDENTIAL"
)
AZURE_USER_AUTHORITY = get_required_env_value("AZURE_USER_AUTHORITY")
AZURE_USER_REDIRECT_URI = get_required_env_value("AZURE_USER_REDIRECT_URI")
AZURE_USER_SCOPES = get_required_env_value("AZURE_USER_SCOPES")

# Azure credentials for database token acquisition
AZURE_DB_CLIENT_ID = get_required_env_value("AZURE_DB_CLIENT_ID")
AZURE_DB_CLIENT_CREDENTIAL = get_required_env_value(
    "AZURE_DB_CLIENT_CREDENTIAL"
)
AZURE_DB_AUTHORITY = get_required_env_value("AZURE_DB_AUTHORITY")
AZURE_DB_SCOPES = get_required_env_value("AZURE_DB_SCOPES")

# Selects the security provider implementation used by EndUserSec middleware
# (for example: "azure_tokens").
DB_SPI_TYPE = get_required_env_value("DB_SPI_TYPE")

# Selects token acquisition flow for DB-side auth (for example: "client_credentials").
DB_AUTH_FLOW = get_required_env_value("DB_AUTH_FLOW")

# Oracle connection pool configuration.
DB_POOL_MIN = get_required_env_value("DB_POOL_MIN")
DB_POOL_MAX = get_required_env_value("DB_POOL_MAX")
DB_POOL_INCREMENT = get_required_env_value("DB_POOL_INCREMENT")

# OCI Generative AI configuration: config file path, inference endpoint,
# and compartment OCID used to authorize requests.
OCI_CONFIG_FILE = get_required_env_value("OCI_CONFIG_FILE")
OCI_ENDPOINT = get_required_env_value("OCI_ENDPOINT")
OCI_COMPARTMENT_ID = get_required_env_value("OCI_COMPARTMENT_ID")

DJANGO_SECRET_KEY = get_required_env_value("DJANGO_SECRET_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = pathlib.Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Enable Oracle Deep Data Security middleware to pass end-user identity
    "oracledb.plugins.end_user_sec_provider.EndUserSecMiddleware",
]


ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.oracle",
        "NAME": sample_env.get_connect_string(),
        "USER": sample_env.get_main_user(),
        "PASSWORD": sample_env.get_main_password(),
        "OPTIONS": {
            "params": sample_env.get_pool_params(),
            "pool": {
                "min": DB_POOL_MIN,
                "max": DB_POOL_MAX,
                "increment": DB_POOL_INCREMENT,
            },
            "extra_auth_params": {
                "end_user_sec_params": {
                    "spi_type": DB_SPI_TYPE,
                    "auth_flow": DB_AUTH_FLOW,
                    "client_id": AZURE_DB_CLIENT_ID,
                    "client_credential": AZURE_DB_CLIENT_CREDENTIAL,
                    "authority": AZURE_DB_AUTHORITY,
                    "scopes": AZURE_DB_SCOPES,
                }
            },
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Azure AD configuration used by the Django application for user sign-in and
# user-token acquisition. Values are sourced from the Azure user authentication
# environment variables defined above.
AZURE_AD = {
    "CLIENT_ID": AZURE_USER_CLIENT_ID,
    "CLIENT_SECRET": AZURE_USER_CLIENT_CREDENTIAL,
    "AUTHORITY": AZURE_USER_AUTHORITY,
    "REDIRECT_URI": AZURE_USER_REDIRECT_URI,
    "SCOPE": AZURE_USER_SCOPES,
}
